tasks:
  - init: |
      pyenv install 3.10.4
      pyenv global 3.10.4
      pip install --upgrade pip
      pip install -r requirements.txt
      curl https://cli-assets.heroku.com/install.sh | sh

vscode:
  extensions:
    - ms-python.python
    - benspaulding.procfile